# Generated by Django 3.2.7 on 2021-11-02 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol_bid_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тип протокола')),
            ],
        ),
        migrations.CreateModel(
            name='Signer_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Роль в согласовании')),
            ],
        ),
        migrations.CreateModel(
            name='Status_bid_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Статус заявки')),
            ],
        ),
        migrations.CreateModel(
            name='Signers_bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=300, verbose_name='Должность согласующего')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО согласующего')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.signer_role')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_bid', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('modified_date_bid', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заявки')),
                ('num_bid', models.TextField(default='ОР-', verbose_name='Заявка')),
                ('source_bid', models.GenericIPAddressField(default='192.168.0.1', verbose_name='Источник')),
                ('recipient_bid', models.GenericIPAddressField(default='192.168.0.2', verbose_name='Получатель')),
                ('port_bid', models.IntegerField(default='3389', verbose_name='Порт')),
                ('persistent_rule', models.BooleanField(default=True, verbose_name='Постоянное правило')),
                ('date_rule_start', models.DateField(blank=True, null=True, verbose_name='Дата начала действия')),
                ('date_rule_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('justification_bid', models.TextField(default='Обоснование', verbose_name='Обоснование')),
                ('description_bid', models.TextField(default='Описание', verbose_name='Описание')),
                ('user_phone_bid', models.TextField(blank=True, default='8-3532-000000', null=True, verbose_name='Телефон исполнителя')),
                ('user_department_name_bid', models.TextField(blank=True, default='Наименование СП исполнителя', null=True, verbose_name='Наименование СП исполнителя')),
                ('boss_department_name_bid', models.TextField(blank=True, default='Наименование СП руководителя', null=True, verbose_name='Наименование СП руководителя')),
                ('boss_full_name_bid', models.TextField(blank=True, default='Фамилия И.О. руководителя', null=True, verbose_name='Фамилия И.О. руководителя')),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('protocol_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.protocol_bid_class')),
                ('status_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status_bid_class')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
