# Generated by Django 3.2.5 on 2021-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bid', models.CharField(default='ОР-', max_length=250, verbose_name='Номер заявки')),
                ('created_date_bid', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('modified_date_bid', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заявки')),
                ('source_bid', models.GenericIPAddressField(verbose_name='Источник')),
                ('recipient_bid', models.GenericIPAddressField(verbose_name='Получатель')),
                ('port_bid', models.IntegerField(default='', verbose_name='Порт')),
                ('protocol_bid', models.CharField(max_length=250, verbose_name='Протокол')),
                ('description_bid', models.TextField(verbose_name='Описание')),
                ('justification_bid', models.TextField(verbose_name='Обоснование')),
            ],
        ),
    ]
