# Generated by Django 3.2.7 on 2021-12-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bid'),
        ),
    ]
