# Generated by Django 3.2.5 on 2021-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='bid',
            name='protocol_bid',
            field=models.CharField(default='TCP', max_length=300, verbose_name='Протокол'),
        ),
    ]
