# Generated by Django 3.2.5 on 2021-08-25 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_bid_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Статус заявки')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='status_bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.status_bid_class'),
            preserve_default=False,
        ),
    ]
