# Generated by Django 3.2.5 on 2021-08-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210728_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol_bid_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='date_rule_end',
            field=models.DateField(auto_now=True, verbose_name='Дата окончания действия'),
        ),
        migrations.AddField(
            model_name='bid',
            name='date_rule_start',
            field=models.DateField(auto_now=True, verbose_name='Дата начала действия'),
        ),
        migrations.AddField(
            model_name='bid',
            name='persistent_rule',
            field=models.BooleanField(default=True, verbose_name='Время действия правила'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='port_bid',
            field=models.IntegerField(default='3389', verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='recipient_bid',
            field=models.GenericIPAddressField(default='192.168.0.2', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='source_bid',
            field=models.GenericIPAddressField(default='192.168.0.1', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='protocol_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.protocol_bid_class'),
        ),
    ]
