# Generated by Django 3.2.7 on 2021-10-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210825_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='boss_department_name_bid',
            field=models.TextField(blank=True, default='Наименование СП руководителя', null=True, verbose_name='Наименование СП руководителя'),
        ),
        migrations.AddField(
            model_name='bid',
            name='boss_full_name_bid',
            field=models.TextField(blank=True, default='Фамилия И.О. руководителя', null=True, verbose_name='Фамилия И.О. руководителя'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user_department_name_bid',
            field=models.TextField(blank=True, default='Наименование СП исполнителя', null=True, verbose_name='Наименование СП исполнителя'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user_phone_bid',
            field=models.TextField(blank=True, default='8-3532-000000', null=True, verbose_name='Телефон исполнителя'),
        ),
    ]
