# Generated by Django 3.2.7 on 2021-12-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rule_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bid'),
        ),
    ]
