# Generated by Django 3.2.7 on 2021-12-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_rule_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='num_bid',
            field=models.TextField(blank=True, null=True, verbose_name='Заявка'),
        ),
    ]
