# Generated by Django 3.2.5 on 2021-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210804_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='persistent_rule',
            field=models.BooleanField(default=True, verbose_name='Постоянное правило'),
        ),
        migrations.AlterField(
            model_name='protocol_bid_class',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Тип протокола'),
        ),
    ]
