# Generated by Django 3.2.5 on 2021-08-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210804_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_rule_end',
            field=models.DateField(verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_rule_start',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
    ]
