# Generated by Django 3.2.7 on 2021-12-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bid_num_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status_bid_class'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bid'),
        ),
    ]
