# Generated by Django 3.2.5 on 2021-08-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210804_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='description_bid',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='justification_bid',
            field=models.TextField(default='Обоснование', verbose_name='Обоснование'),
        ),
    ]
