# Generated by Django 3.2.5 on 2021-08-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bid_auth_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auth_user_id',
            new_name='auth_user',
        ),
    ]
