# Generated by Django 3.2.5 on 2021-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_auth_user_id_bid_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='id',
        ),
        migrations.AlterField(
            model_name='bid',
            name='num_bid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
